### ISSUE TITLE
GHC 7.10.1 -- compiling huge HashSet hogs memory

### ISSUE THREAD

**Issue by zudov** [tibbe/unordered-containers#100] opened 2015-04-11 15:10 UTC
Compiling a huge (~2.5k elements) set with GHC-7.10.1 or GHC-head and unordered-containers-0.2.5.1 or unordered-containers-head.

Here is a [file](https://github.com/zudov/html5-entity/blob/unordered-containers/src/Text/Html/Entity/Data/EntitySet.hs) which I am trying to compile. I've also set up a [travis build](https://travis-ci.org/zudov/html5-entity/builds/58063328) which demonstrates the behaviour with different versions of GHC and unordered-containers. Further I would be referring to [this build-job](https://travis-ci.org/zudov/html5-entity/jobs/58063332) which uses GHC-7.10.1 and unordered-containers-0.2.5.1.

- [Compilation](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L397) with default optimization options takes around [12GB](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L408) of memory.
- [Compilation](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L367) with `-O0` takes around [400MB](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L378).
- [Compilation](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L457) with `-O2` takes around [12GB](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L468) of memory.
- [Compilation](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L487) with `-O2 -fignore-interface-pragmas` takes around [500MB](https://travis-ci.org/zudov/html5-entity/jobs/58063332#L498) of memory, which solves the problem.

When the build uses GHC-7.8.4, neither of this hogging [occurs](https://travis-ci.org/zudov/html5-entity/jobs/58063330).

Another interesting observation is that [compiling](https://travis-ci.org/zudov/html5-entity/jobs/58063330#L339) [`HashMap`](https://github.com/zudov/html5-entity/blob/unordered-containers/src/Text/Html/Entity/Data/EntityMap.hs) of the same size, doesn't cause memory hogging even with `-O2`. This attracted my attention as `HashSet` is implemented in terms of `HashMap`.

I am not completely sure if an issue is with GHC or `unordered-containers` but it seems more likely to be here. Also, if it's a GHC bug you would be able to identify it better than me.

**Comment by tibbe** [comment] 2015-04-12 11:50
Thanks for the detailed report. Do you mind filing this as a bug against GHC at https://ghc.haskell.org/trac/ghc?

**Comment by zudov** [comment] 2015-04-12 12:43
Sure

**Comment by zudov** [comment] 2015-04-12 13:38
https://ghc.haskell.org/trac/ghc/ticket/10291#ticket

**Comment by tibbe** [comment] 2015-04-12 14:27
Thanks! I will close this since it's a GHC regression.

**Closed by tibbe** 2015-04-12 14:27 UTC
